### PR TITLE
Fix building of tigl with python 3.9

### PR DESCRIPTION
**Pull request by rainman110**
This integrates a patch that tries to fix build issues with python 3.9.

Also, i changed the checkout behavior to avoid converting line endings, as this messes up the patches.

### CODE REVIEW

**Comment by rainman110** [comment]
The commits should probably be squased when merging.

**Comment by joergbrech** [comment]
We should change this line to `pull_request`:

https://github.com/DLR-SC/tigl-conda/blob/021830471e73301710b3a4b4607eb404b19b17b1/.github/workflows/build-conda-packages.yml#L7

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Firstly, it is an unnecessary security risk and secondly, the workflow triggered by `pull_request_target` runs without the local changes to the Workflow file (git line endings policy).

**Comment by rainman110** [comment]
Can I change this in the current branch or does this have to be done on master?

**Comment by joergbrech** [comment]
> Can I change this in the current branch or does this have to be done on master?

Umm. good question. I am not sure how this will effect this PR 😄 I guess the consequences are clear if we change it on master and then rebase this PR-branch on that change?

**Comment by rainman110** [comment]
I forced push the commit "Try to fix patch apply" which succeeded on CI: https://github.com/DLR-SC/tigl-conda/actions/runs/1475522462

Strangely, this is not reflected here on the commit list.

**Comment by rainman110** [comment]
> 
> 
> > Can I change this in the current branch or does this have to be done on master?
> 
> Umm. good question. I am not sure how this will effect this PR 😄 I guess the consequences are clear if we change it on master and then rebase this PR-branch on that change?

Good idea!

**Review by joergbrech — APPROVED** [review]

**Pull request merged**
