### PR TITLE
Build tixi3 with Fortran suppoert

### PR DESCRIPTION
**Pull request by melven**
Re-enable Fortran support in tixi3 conda package as we need the generated Fortran 2003 wrapper file in another project.

### CODE REVIEW

**Comment by joergbrech** [comment]
@melven, any ideas why the windows builds fail?

**Comment by rainman110** [comment]
Github switched to windows server 2022 a couple of days ago. You might want to switch from windows-latest to windows-2019

**Comment by melven** [comment]
Similar problem occurs for builds in https://github.com/DLR-SC/tixi ...

**Comment by joergbrech** [comment]
Could you please rebase on your branch `melven:switch_ci_to_windows2019`, or on master once #23 is merged?

**Pull request merged**
